# Generated by Django 3.2.5 on 2022-01-04 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=20)),
                ('domain_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=20)),
                ('sequence', models.CharField(max_length=256)),
                ('length', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_id', models.CharField(max_length=20)),
                ('clade', models.CharField(default='E', max_length=1)),
                ('genus', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomainsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organism_api.domains')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organism_api.protein')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='domains',
            field=models.ManyToManyField(through='organism_api.ProteinDomainsLink', to='organism_api.Domains'),
        ),
        migrations.AddField(
            model_name='protein',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organism_api.taxonomy'),
        ),
        migrations.AddField(
            model_name='domains',
            name='pfam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organism_api.pfam'),
        ),
    ]
