# Generated by Django 3.2.5 on 2022-01-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domains',
            new_name='Domain',
        ),
        migrations.RenameModel(
            old_name='ProteinDomainsLink',
            new_name='Domain_protein_link',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='pfam',
            new_name='pfam_id',
        ),
        migrations.AlterField(
            model_name='pfam',
            name='domain_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='protein',
            name='length',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='protein',
            name='protein_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='taxa_id',
            field=models.CharField(max_length=30),
        ),
    ]
