# Generated by Django 4.0.1 on 2022-01-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organism_api', '0003_auto_20220109_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain_protein_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organism_api.domain')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organism_api.protein')),
            ],
        ),
    ]
